
##################################################
#                                                #
#                  Codis-Fe                      #
#                                                #
##################################################
# Startup config.
# Set the listen address.
listen = ""

# Set runtime.GOMAXPROCS to N, default is 1.
ncpu = 1

# Set path/name of daliy rotated log file.
log = "./fe.log"

# Expire-log-days, 0 means never expire
expire_log_days = 30

# Set pidfile name
pidfile = "fe.pid"

# Set the log-level, should be INFO,WARN,DEBUG or ERROR, default is INFO.
log_level = "info"

# Set list of dashboard.
dashboard_list = ""

# Set mysql server (such as localhost:3306), fe will report user info and codis info to mysql.
mysql_addr = ""
mysql_username = ""
mysql_password = ""
mysql_database = ""
